services:
  - type: web
    name: meddesk-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        fromDatabase:
          name: meddesk-db
          property: connectionString
    healthCheckPath: /api/health

databases:
  - name: meddesk-db
    plan: free
